# example 2: on merge to master from pull request (recommended)
name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"

      - name: Bump version and push tag
        id: github_tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_SUPER }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          # PRERELEASE: true
          # DEFAULT_BUMP: patch
          # RELEASE_BRANCHES: main, release, hotfix

      - name: Print version
        env:
          NEW_TAG: ${{ steps.github_tag.outputs.new_tag }}
          TAG: ${{ steps.github_tag.outputs.tag }}
          PART: ${{ steps.github_tag.outputs.part }}
        run: |
          echo  "New tag: $NEW_TAG"
          echo  "Tag: $TAG"
          echo  "Part: $PART"
